### PR TITLE
Laravel 5.2 example

### PR DESCRIPTION
**Pull request by komita1981**
Hi Domenic,
I created working example for Laravel 5.2 version. It's easier to work with model factories now. I also added DB transactions before and after each method. I am open for all kind of discussions - I found this way is the most appropriate to say thank you for this package :-)

### CODE REVIEW

**Comment by ddelnano** [comment]
Hey I really appreciate the contribution!  I think it looks great and definitely more of the "laravel" way than using the Manager class directly like I did.

I just want to update the wiki to reflect your example.  I probably won't have time tonight to make those changes but sometime tomorrow I will make those changes and get this merged!  Thanks again!

**Comment by ddelnano** [comment]
Was really busy with work stuff, but will have this done today

**Comment by komita1981** [comment]
There is no need to hurry :-)

**Comment by ddelnano** [comment]
Sorry for the wait, looks good to me and the wiki is now updated!  Thanks again for the contribution and I am glad you find the package useful!

**Comment by netmilk** [comment]
@ddelnano @komita1981 This is awesome!!! It would be great if it could be part of the main Dredd [documentation](https://github.com/apiaryio/dredd/blob/master/docs/hooks-php.md)... Would you mind filing a PR there? And it could be great topic for a blogpost/tutorial, btw. It's possible to publish it on the Apiary blog if you guys were interested.

**Comment by ddelnano** [comment]
Yea I think that is a great idea.  @komita1981 if you want to do that go ahead or else I can.

**Comment by komita1981** [comment]
@netmilk @ddelnano This is awesome idea. We will do something about this - I have some ideas - I will contact you Domenic.

**Comment by ddelnano** [comment]
@netmilk. @komita1981 and I met earlier today and we are in the process of beginning the blog post.

**Comment by netmilk** [comment]
@ddelnano @komita1981 That's great news! Let me know if I can help!

**Pull request merged**
