### PR TITLE
Update documentation on transaction support

### PR DESCRIPTION
**Pull request by ddelnano**
@spawnia sorry for taking incredibly long on this and also taking this to my own branch.  I realized I wasn't happy with the rest of the example docs and also that I wanted some additional cleanup.  Can you give this a look over and make sure it addresses all your concerns?

### CODE REVIEW

**Review by spawnia — CHANGES_REQUESTED** [review]
I would add the `--seed` flag to the migrations. It is generally not useful to do API tests on an empty database.

**Comment by ddelnano** [comment]
@spawnia as opposed to seeding on a "per test" basis like I have?  There definitely is data in the database when that one transaction runs.

**Comment by ddelnano** [comment]
I did test that the example runs properly.

**Comment by spawnia** [comment]
Oh my bad, i missed that. Setting up the database on a per-test basis seems like it would be a lot of work when testing a more complex api. That is why i choose to have a common seed in which i populate multiple tables. It certainly depends on the use case, your approach works fine here.

From my point of view this can be merged, as it sure helps to clarify the issue.

**Comment by ddelnano** [comment]
Thanks for sticking with this despite me taking forever!

**Comment by spawnia** [comment]
Closes #34

**Pull request merged**
